### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Sharaddition** [Mobile-Artificial-Intelligence/piper_tts#1]
Hey, I was wondering if we can use this package right now? If so, then please update readme. Thanks for porting it!

**Comment by danemadsen** [comment]
It currently works on linux and windows only, wont compile for android and will need some work to get it to.

**Comment by Sharaddition** [comment]
Ohh, I needed currently for Android. 
Btw, I have an issue: I'm unable to install piper on windows ([due to piper-phonemize](https://github.com/rhasspy/piper/issues/157#event-9992449547)), do you have any solution?
Sorry it's offtopic. Don't mind to close.

**Comment by danemadsen** [comment]
Yeah I had the same issue. I solved it by just including piper phonemizes files directly in pipers repo. You should be able to compile it using this.

https://github.com/Mobile-Artificial-Intelligence/piper.cpp

With regards,
Dane Madsen
________________________________

**Comment by Sharaddition** [comment]
Thanks for the help, closing it for now.
